name: Flutter build apk pipeline

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]

  pull_request:
    branches: [main]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    name: flutter build
    runs-on: ubuntu-latest
    env:
      JAVA_VERSION: '12.x'
      FLUTTER_VERSION: '2.2.2'
      FLUTTER_CHANNEL: 'stable'
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: ${{env.JAVA_VERSION}}

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{env.FLUTTER_VERSION}}
          channel: ${{env.FLUTTER_CHANNEL}}

      - name: Pub Get Packages
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --split-per-abi

      - name: Create Github Release
        uses: actions/upload-artifact@v2
        with:
          name: app-release
          path: build/app/outputs/apk/release
